README.md

Added small text about the mailing list in the README

---

src/Nbody/Sinks.cpp

Silly bug - yet a showstopper...

Solved bug in accretion

---

src/Common/Ewald.cpp
src/Common/Exception.cpp
src/Common/IC.cpp
src/Common/gandalf.cpp
src/Headers/DomainBox.h
src/Hydrodynamics/EnergyRadws.cpp
src/Hydrodynamics/RiemannSolver.cpp
src/Hydrodynamics/SphIntegration.cpp
src/Hydrodynamics/SphSimulation.cpp
src/MeshlessFV/MeshlessFVSimulation.cpp
src/Nbody/NbodySystemTree.cpp
src/Nbody/Sinks.cpp
src/Radiation/TreeRay.cpp
src/Thermal/MonochromaticIonisationMonteCarlo.cpp
src/Thermal/TreeMonteCarlo.cpp
src/Tree/KDRadiationTree.cpp
src/Tree/KDTree.cpp
src/Tree/OctTree.cpp
src/Tree/Tree.cpp

Replaced as many exit statements with exceptions as I thought safe to do so.  There are still a few exits, but they are either in Exception.cpp file (which I believe need to be there) or in the chealpix.c file (which I don't want to touch atm).

- Replaced all/most exit(0) statements with throwing exceptions

---

src/Common/IC.cpp
src/Headers/IC.h

When using openmp and using cubic/hex lattice in initial conditions

Corrected bug when using Intel compiler

---

src/GradhSph/GradhSphTree.cpp
src/Hydrodynamics/SphSimulation.cpp
src/Nbody/Sinks.cpp
src/Tree/HydroTree.cpp

Fixed memory leak problem with gravity tree.  Not icpc specific, but showed up on test runs on c2pap.

Icpc debug

---

src/Hydrodynamics/Ghosts.cpp

Look at the diff - should be straightforward to see why this can be merged.

Added reflection for velocity when copying mirror ghosts

---

src/Common/gandalf.cpp
src/Headers/InlineFuncs.h
src/Hydrodynamics/SphSimulation.cpp

This is trivial enough that I think we should merge it immediately

Error checking

---

analysis/facade.py

I cherry picked the commit from the getanalytical branch. That one is not straightforward to merge because it depends on tests. This one instead is trivial and can be merged immediately.
I'll now delete getanalytical as it is useless at this stage

Added function to get the analytical data

---

src/GradhSph/GradhSph.cpp

This is the missing energy fix

Fixed error in energy integration with SPH and self-gravity

---

src/GradhSph/GradhSphTree.cpp
src/Headers/BruteForceTree.h
src/Headers/CommunicationHandler.h
src/Headers/KDTree.h
src/Headers/MeshlessFV.h
src/Headers/NeighbourSearch.h
src/Headers/OctTree.h
src/Headers/Particle.h
src/Headers/Tree.h
src/Hydrodynamics/Ghosts.cpp
src/Hydrodynamics/Hydrodynamics.cpp
src/Hydrodynamics/SphSimulation.cpp
src/MeshlessFV/MeshlessFV.cpp
src/MeshlessFV/MeshlessFVSimulation.cpp
src/MeshlessFV/MeshlessFVTree.cpp
src/MeshlessFV/MfvCommon.cpp
src/MeshlessFV/MfvMusclSimulation.cpp
src/Mpi/MpiControl.cpp
src/Mpi/MpiKDTreeDecomposition.cpp
src/Mpi/MpiTree.cpp
src/Tree/BruteForceTree.cpp
src/Tree/HydroTree.cpp
src/Tree/KDTree.cpp
src/Tree/OctTree.cpp
src/Tree/Tree.cpp

MPI is working now as far as I can tell (although I didn't test all the edge cases yet). Gravity needs to zero a and gpot, which was not done previously. I temporarily did it just before the force calculation, but there should be a better place clearly. I guess EndTimestep would be the right place, can you confirm?
I'll also go one last time through the main loop and check that the ghosts are always up to date (and remove unnecessary updates), we are still doing too many updates (possibly also failing to do necessary ones, although I should have fixed that).

Mpi meshlessclean

---

tests/dust_tests/dustywave.dat
tests/dust_tests/dustywave_sol.py
tests/dust_tests/test_dustywave.py
tests/to_run

I've added the dusty wave test to the correctness tests, which should be ready to merge with test_correctness branch

Dustywave test

---

src/Common/Simulation.cpp
src/GradhSph/GradhSphSimulation.cpp
src/Headers/DomainBox.h
src/Headers/InlineFuncs.h
src/Headers/MpiControl.h
src/Headers/Tree.h
src/Hydrodynamics/SphSimulation.cpp
src/MeshlessFV/MeshlessFVSimulation.cpp
src/MeshlessFV/MfvMusclSimulation.cpp
src/Mpi/MpiControl.cpp
src/Mpi/MpiKDTreeDecomposition.cpp
src/Mpi/MpiTree.cpp
src/Tree/BruteForceTree.cpp
src/Tree/HydroTree.cpp
src/Tree/OctTree.cpp
src/Tree/Tree.cpp

Tree loadbalancing

---

src/GradhSph/GradhSph.cpp
src/Headers/Hydrodynamics.h
src/Headers/MeshlessFV.h
src/Headers/NeighbourManager.h
src/Headers/Sph.h
src/Hydrodynamics/RiemannSolver.cpp
src/MeshlessFV/MeshlessFV.cpp
src/SM2013/SM2012Sph.cpp

Removed duplicate copies of DeleteDeadParticles using a template implementation. See #103

Delete dead particles

---

src/Headers/Nbody.h
src/Ic/Ic.cpp
src/Nbody/Nbody.cpp
src/Nbody/NbodyHermite4.cpp
src/Nbody/NbodyHermite6TS.cpp
src/Nbody/NbodyLeapfrogDKD.cpp
src/Nbody/NbodyLeapfrogKDK.cpp
src/Nbody/NbodySystemTree.cpp
tests/paper_tests/freefalltest.py
tests/paper_tests/hybridplummer.dat
tests/paper_tests/plummer.dat
tests/paper_tests/plummertest.py

Small pull request with some small fixes and modifications to the N-body parts, including : 
- Fix for identifying binary stars (was using centre of position instead of centre of mass)
- Parallelised intensive parts of N-body with OpenMP finally
Also added files and scripts to generate star-only and hybrid plummer spheres, run their simulations and generate figures for the paper.

Nbody fixes and paper figure scripts

---

src/Headers/RiemannSolver.h

I realized that the HLL Riemann solver does not correctly capture shear waves, so I've now implemented an HLLC like solver that has a constant density as well as pressure and velocity in the mid-state, but allows the transverse velocities to vary. This option is only switched on when the simulation is 'isothermal'. It should work for both the isothermal and locally isothermal EoS. 
While the solver is idealistically better, in some simple tests I can't see any difference...

Added back shear waves with isothermal Riemann solver

---

README.md
docs/userguide.tex
src/Common/Simulation.cpp

Acknowledge richard

---

tests/dust_tests/dustywave_sol.py
tests/paper_tests/dustybox.dat
tests/paper_tests/dustyboxtest.py
tests/paper_tests/dustywave.dat
tests/paper_tests/dustywavetest.py

I've added a couple of paper tests that were missing, we should probably include them.

Added missing paper tests

---

docs/userguide.tex
src/MeshlessFV/MeshlessFVSimulation.cpp
src/MeshlessFV/MeshlessFVTree.cpp
src/MeshlessFV/MfvIntegration.cpp
src/MeshlessFV/MfvMuscl.cpp

I made the gravitational update now use the conservative change in the centre of mass with the MFV scheme.  However, it still does not work well...

Made rdmdt conservative

---

src/Common/Simulation.cpp
src/Common/SimulationIO.hpp
src/Mpi/MpiKDTreeDecomposition.cpp

There were some bugs with failed restarts and MPI, and some incorrect data types.

Fixed bug with mpi types and restart

---

src/Common/Parameters.cpp
src/Headers/SimUnits.h
src/Ic/DiscIc.cpp

This pull request allows the disc test to run with non dimensionless units. Please check that it makes sense!

Allowed disc to run with non-dimensionless units
